name: Create Version Number2

on:
    workflow_call:

jobs:
    print-hello-world:
        runs-on: windows-latest
        steps:
            - name: Print Hello World2
              run: echo "Hello, World2!"

              